//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KStar.Form.Mvc.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KStarForm_Prompt {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KStarForm_Prompt() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KStar.Form.Mvc.App_GlobalResources.KStarForm_Prompt", typeof(KStarForm_Prompt).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 审批失败 的本地化字符串。
        /// </summary>
        internal static string ApproveFailure {
            get {
                return ResourceManager.GetString("ApproveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审批成功 的本地化字符串。
        /// </summary>
        internal static string ApproveSuccessfully {
            get {
                return ResourceManager.GetString("ApproveSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消沟通失败 的本地化字符串。
        /// </summary>
        internal static string CancelCommunicateFailure {
            get {
                return ResourceManager.GetString("CancelCommunicateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消沟通成功 的本地化字符串。
        /// </summary>
        internal static string CancelCommunicateSuccessfully {
            get {
                return ResourceManager.GetString("CancelCommunicateSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消失败 的本地化字符串。
        /// </summary>
        internal static string CancelFailure {
            get {
                return ResourceManager.GetString("CancelFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消订阅失败 的本地化字符串。
        /// </summary>
        internal static string CancelSubscribeFailure {
            get {
                return ResourceManager.GetString("CancelSubscribeFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消订阅成功 的本地化字符串。
        /// </summary>
        internal static string CancelSubscribeSuccessfully {
            get {
                return ResourceManager.GetString("CancelSubscribeSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作废成功 的本地化字符串。
        /// </summary>
        internal static string CancelSuccessfully {
            get {
                return ResourceManager.GetString("CancelSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传阅失败 的本地化字符串。
        /// </summary>
        internal static string CirculateFailure {
            get {
                return ResourceManager.GetString("CirculateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传阅成功 的本地化字符串。
        /// </summary>
        internal static string CirculateSuccessfully {
            get {
                return ResourceManager.GetString("CirculateSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 沟通反馈失败 的本地化字符串。
        /// </summary>
        internal static string CommunicateFeedbackFailure {
            get {
                return ResourceManager.GetString("CommunicateFeedbackFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 沟通反馈成功 的本地化字符串。
        /// </summary>
        internal static string CommunicateFeedbackSuccessfully {
            get {
                return ResourceManager.GetString("CommunicateFeedbackSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 沟通失败 的本地化字符串。
        /// </summary>
        internal static string CommunicationFailure {
            get {
                return ResourceManager.GetString("CommunicationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 沟通成功 的本地化字符串。
        /// </summary>
        internal static string CommunicationSuccessfully {
            get {
                return ResourceManager.GetString("CommunicationSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表单状态为已提交，请勿重复提交！ 的本地化字符串。
        /// </summary>
        internal static string FormIDRepeatSubmit {
            get {
                return ResourceManager.GetString("FormIDRepeatSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取失败 的本地化字符串。
        /// </summary>
        internal static string GetFailure {
            get {
                return ResourceManager.GetString("GetFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取成功 的本地化字符串。
        /// </summary>
        internal static string GetSuccessfully {
            get {
                return ResourceManager.GetString("GetSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您没有权限打开此表单！ 的本地化字符串。
        /// </summary>
        internal static string NoOpenFormAuthority {
            get {
                return ResourceManager.GetString("NoOpenFormAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转办失败 的本地化字符串。
        /// </summary>
        internal static string RedirectFailure {
            get {
                return ResourceManager.GetString("RedirectFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转办成功 的本地化字符串。
        /// </summary>
        internal static string RedirectSuccessfully {
            get {
                return ResourceManager.GetString("RedirectSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拒绝失败 的本地化字符串。
        /// </summary>
        internal static string RefusedFailure {
            get {
                return ResourceManager.GetString("RefusedFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拒绝成功 的本地化字符串。
        /// </summary>
        internal static string RefusedSuccessfully {
            get {
                return ResourceManager.GetString("RefusedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 驳回失败 的本地化字符串。
        /// </summary>
        internal static string RejectFailure {
            get {
                return ResourceManager.GetString("RejectFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 驳回成功 的本地化字符串。
        /// </summary>
        internal static string RejectSuccessfully {
            get {
                return ResourceManager.GetString("RejectSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新提交失败 的本地化字符串。
        /// </summary>
        internal static string ReSubmitFailure {
            get {
                return ResourceManager.GetString("ReSubmitFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新提交成功 的本地化字符串。
        /// </summary>
        internal static string ReSubmitSuccessfully {
            get {
                return ResourceManager.GetString("ReSubmitSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存失败 的本地化字符串。
        /// </summary>
        internal static string SaveDraftFailure {
            get {
                return ResourceManager.GetString("SaveDraftFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功 的本地化字符串。
        /// </summary>
        internal static string SaveDraftSuccessfully {
            get {
                return ResourceManager.GetString("SaveDraftSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交流程失败 的本地化字符串。
        /// </summary>
        internal static string SubmitFailure {
            get {
                return ResourceManager.GetString("SubmitFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交成功 的本地化字符串。
        /// </summary>
        internal static string SubmitSuccessfully {
            get {
                return ResourceManager.GetString("SubmitSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订阅失败 的本地化字符串。
        /// </summary>
        internal static string SubscribeFailure {
            get {
                return ResourceManager.GetString("SubscribeFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订阅成功 的本地化字符串。
        /// </summary>
        internal static string SubscribeSuccessfully {
            get {
                return ResourceManager.GetString("SubscribeSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 撤回失败 的本地化字符串。
        /// </summary>
        internal static string WithdrawnFailure {
            get {
                return ResourceManager.GetString("WithdrawnFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 撤回成功 的本地化字符串。
        /// </summary>
        internal static string WithdrawnSuccessfully {
            get {
                return ResourceManager.GetString("WithdrawnSuccessfully", resourceCulture);
            }
        }
    }
}
